Feature/tests generator tool
SimplrJS/ts-docs-gen pull request #6
Opened 2017-12-12 17:07 UTC by DonatasBrazionis

2017-12-13 14:39 UTC, MartynasZilinskas approved these changes

2017-12-18 10:06 UTC, DeividasBakanas requested changes

2017-12-18 10:06 UTC, DeividasBakanas commented on tools/test-generator-cli/src/cli-arguments.ts
> +    .option("path", {
Consider renaming to "project".

2017-12-18 10:06 UTC, DeividasBakanas commented on tools/test-generator-cli/src/index.ts
> +    let cwd: string;
Can be replaced with:
```ts
const cwd = argumentObject.path || process.cwd();
```

2017-12-18 10:06 UTC, DeividasBakanas commented on tools/test-generator-cli/src/tests-generator.ts
> +    const casesDirPaths = await fastGlob([
Reconsider formatting:

```ts
const casesDirPaths = await fastGlob(
    [
        `${testsCasesPath}/*`
    ],
    {
        onlyDirs: true,
        ignore: [`**/${GENERATED_TESTS_DIR_NAME}/**`]
    }
);
```

or 

```ts
const casesDirPaths = await fastGlob(
    [`${testsCasesPath}/*`],
    {
        onlyDirs: true,
        ignore: [`**/${GENERATED_TESTS_DIR_NAME}/**`]
    }
);
```

2017-12-18 10:06 UTC, DeividasBakanas commented on tools/test-generator-cli/src/tests-helpers.ts
> +export function Tab(size: number = 1): string {
Is this helper still useful?

2017-12-18 11:52 UTC, DeividasBakanas approved these changes

2017-12-18 12:47 UTC, merged